### ISSUE TITLE
When rejecting an item array loses my attached event listeners 

### ISSUE THREAD

**Issue by marcelklehr** [matthewmueller/array#1]

**Comment by marcelklehr** [comment]
Mh.. unless that's intentional.. using splice(indexof, 1) now, hope that works

**Comment by matthewmueller** [comment]
Hmm.. do you have events attached onto the array itself? Or objects within the array?

**Comment by marcelklehr** [comment]
I had attached an event listener on the array object, but as `.reject` returns a newly created object those listeners were lost

**Comment by marcelklehr** [comment]
But that behavior is probably intentional. I just assumed i could mutate the array directly using those enumerable methods.. turns out i can't. So, i'm using `.splice` now..

**Comment by matthewmueller** [comment]
Okay right. Yah, I was trying to decide between updating just reinitializing. Updating is probably a better choice. I'll fix that.

**Comment by marcelklehr** [comment]
Noo! There are cases where you want your main array to be left as it is but iterate only over certain items. If you're fixing `.reject` to mutate the array directly, the main array will loose data!

**Comment by matthewmueller** [comment]
Haha, what downside do you see in updating?

**Comment by marcelklehr** [comment]
My suggestion is to document which methods mutate the array directly and which ones return a new one (thus removing any event listeners)
