### ISSUE TITLE
Operations should be non-destructive

### ISSUE THREAD

**Issue by Swatinem** [matthewmueller/array#18]
Once I was using `array` as a drop-in-replacement for native `Array`, just to pull my hair out later because `.map()` actually overwrites the original array instead of creating a new one like all the functional extras of native `Array` do.

https://github.com/MatthewMueller/array/commit/586bd7a5bbdff8c77b37191c5d5209d264453392 goes even further than this, also breaking this rule for `.filter()`

I think thats a big mistake. It breaks things like:

``` js
var values = array([…]);

var withPropA = values.filter(…);
var withPropB = values.filter(…);
```

Please rethink this decision and make it possible to use this as a more or less drop-in-replacement for native `Array` with all the functional programming guarantees.

**Comment by Swatinem** [comment]
I mean I understand the reasoning behind this change. But its rather an edge-case to add custom properties to arrays. I don’t think that happens in the real world.
And even if someone does it (with a native `Array`), they still have to deal with these custom properties disappearing when using functional extras like `.map()` and `.filter()`.

**Comment by Swatinem** [comment]
So the question really comes down to what you want to do:

1) Have a better `Array` with events and `to-function` support for all the methods.
2) The ability to transform arbitrary objects into array-like things.

The first one is exactly my usecase and I would think also the more common one.
The second usecase is already broken for native `Array` and simply bad practice anyway, don’t you think?

**Comment by matthewmueller** [comment]
@Swatinem thanks for reporting this, this was a mistake. I should have fixed this in master. Now the original context is preserved but the array contents are non-destructive.
