### ISSUE TITLE
Interrupt .each(fn) in fn

### ISSUE THREAD

**Issue by nickeljew** [matthewmueller/array#31]
I checked the codes and found no way to stop .each function in fn. If some conditions are not fulfilled, the process is not necessary to continue.
As a matter of fact, JQuery implement this requirement, and the enumeration may be interrupted if return value of fn as false.

**Comment by Swatinem** [comment]
Use .every() and return something falsy. (you have to return something truthy to continue though)

**Comment by nickeljew** [comment]
Thanks, but I did not find info about .every() in Readme.md, and have to look for it in codes.
