### ISSUE TITLE
Failed to install (emitter and to-function) on Node 0.8.8

### ISSUE THREAD

**Issue by assassinacc** [matthewmueller/array#8]
CMD "npm install array.js":

[...]
119 error Error: No compatible version found: emitter@'component/emitter'
119 error Valid install targets:
119 error ["0.0.2","0.0.1"]
119 error     at installTargetsError (/package/host/localhost/nodejs-0.8.8/lib/node_modules/npm/lib/cache.js:553:10)
119 error     at /package/host/localhost/nodejs-0.8.8/lib/node_modules/npm/lib/cache.js:477:15
119 error     at saved (/package/host/localhost/nodejs-0.8.8/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
119 error     at /package/host/localhost/nodejs-0.8.8/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:220:7
119 error     at Object.oncomplete (fs.js:297:15)
[...]
121 error System Linux 2.6.32-279.5.2.el6.x86_64
122 error command "/package/host/localhost/nodejs-0.8.8/bin/node" "/package/host/localhost/nodejs-0.8.8/bin/npm" "install" "array.js"
124 error node -v v0.8.8
125 error npm -v 1.1.59

**Comment by matthewmueller** [comment]
can you update your version of npm and try again? I think the github version syntax was introduced after 1.1.59.

**Comment by matthewmueller** [comment]
okay, latest release definitely resolves this.

**Comment by assassinacc** [comment]
yes, it works. thank you.
